#!/bin/bash
ua="Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_3 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5"

curl --insecure --cookie "disclaimer_accepted=true&tor2web_header_hidden=true" -A "$ua" -L https://duskgytldkxiuqc6.tor2web.fi/
